### ISSUE TITLE
DPropertiesI: schema:name - is it used anywhere?

### ISSUE THREAD

**Issue by olga-kovalenko** [i40-Tools/vocabularies#17]

**Comment by igrangel** [comment]
Is a good practice to reuse existing and well-known vocabularies. (schema.org)[http://schema.org/] is one of them. For this reason I started using this property because is a general property to describe names. Still I think we should specialized it in our context. We could create a subproperty for this. What do you think?

**Comment by olga-kovalenko** [comment]
Yes, sounds good to me! 
Like hasID being a subproperty or having a link "sameAs" to the "dc:identifier", right?
