### ISSUE TITLE
DPropertiesI: dc:identifier & dc:title

### ISSUE THREAD

**Issue by olga-kovalenko** [i40-Tools/vocabularies#18]
I am not sure what is intended meaning of those properties and how/whether they are used

**Comment by igrangel** [comment]
Similarly to https://github.com/i40-Tools/vocabularies/issues/17 it is an intent to reuse well-known vocabularies, in this case, [Dublin Core](http://dublincore.org/documents/2012/06/14/dcmi-terms/) since Identifier are very important for the AML domain we can think in reusing [dc:identifier](http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=elements#identifier). My proposal is to specialize it.

**Comment by olga-kovalenko** [comment]
I see, yes, this is a good idea :)
